version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - "burov"
      - "dowgird"
      - "ekremenetskii"
      - "Gulio"
      - "MahmoudOuka"
      - "MarcMarc"
      - "michaljankowiak"
      - "paulinakania"
