version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    labels:
      - dependencies
      - go
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
reviewers:
  - burov
  - dowgird
  - Gulio
  - michaljankowiak
  - paulinakania
  - ekremenetskii
  - MahmoudOuka
  - MarcMarc
