//  Copyright 2026 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: /usr/local/google/home/pcieslak/git/osconfig/agentendpoint/agentendpoint.go

// Package utilmocks is a generated GoMock package.
package utilmocks

import (
	context "context"
	reflect "reflect"

	agentendpointpb "cloud.google.com/go/osconfig/agentendpoint/apiv1/agentendpointpb"
	gomock "github.com/golang/mock/gomock"
	gax "github.com/googleapis/gax-go/v2"
	grpc "google.golang.org/grpc"
)

// MockAgentEndpointClient is a mock of AgentEndpointClient interface.
type MockAgentEndpointClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgentEndpointClientMockRecorder
}

// MockAgentEndpointClientMockRecorder is the mock recorder for MockAgentEndpointClient.
type MockAgentEndpointClientMockRecorder struct {
	mock *MockAgentEndpointClient
}

// NewMockAgentEndpointClient creates a new mock instance.
func NewMockAgentEndpointClient(ctrl *gomock.Controller) *MockAgentEndpointClient {
	mock := &MockAgentEndpointClient{ctrl: ctrl}
	mock.recorder = &MockAgentEndpointClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentEndpointClient) EXPECT() *MockAgentEndpointClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAgentEndpointClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAgentEndpointClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAgentEndpointClient)(nil).Close))
}

// Connection mocks base method.
func (m *MockAgentEndpointClient) Connection() *grpc.ClientConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connection")
	ret0, _ := ret[0].(*grpc.ClientConn)
	return ret0
}

// Connection indicates an expected call of Connection.
func (mr *MockAgentEndpointClientMockRecorder) Connection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connection", reflect.TypeOf((*MockAgentEndpointClient)(nil).Connection))
}

// ReceiveTaskNotification mocks base method.
func (m *MockAgentEndpointClient) ReceiveTaskNotification(arg0 context.Context, arg1 *agentendpointpb.ReceiveTaskNotificationRequest, arg2 ...gax.CallOption) (agentendpointpb.AgentEndpointService_ReceiveTaskNotificationClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReceiveTaskNotification", varargs...)
	ret0, _ := ret[0].(agentendpointpb.AgentEndpointService_ReceiveTaskNotificationClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveTaskNotification indicates an expected call of ReceiveTaskNotification.
func (mr *MockAgentEndpointClientMockRecorder) ReceiveTaskNotification(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveTaskNotification", reflect.TypeOf((*MockAgentEndpointClient)(nil).ReceiveTaskNotification), varargs...)
}

// RegisterAgent mocks base method.
func (m *MockAgentEndpointClient) RegisterAgent(arg0 context.Context, arg1 *agentendpointpb.RegisterAgentRequest, arg2 ...gax.CallOption) (*agentendpointpb.RegisterAgentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterAgent", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.RegisterAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAgent indicates an expected call of RegisterAgent.
func (mr *MockAgentEndpointClientMockRecorder) RegisterAgent(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAgent", reflect.TypeOf((*MockAgentEndpointClient)(nil).RegisterAgent), varargs...)
}

// ReportInventory mocks base method.
func (m *MockAgentEndpointClient) ReportInventory(arg0 context.Context, arg1 *agentendpointpb.ReportInventoryRequest, arg2 ...gax.CallOption) (*agentendpointpb.ReportInventoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReportInventory", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.ReportInventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportInventory indicates an expected call of ReportInventory.
func (mr *MockAgentEndpointClientMockRecorder) ReportInventory(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportInventory", reflect.TypeOf((*MockAgentEndpointClient)(nil).ReportInventory), varargs...)
}

// ReportTaskComplete mocks base method.
func (m *MockAgentEndpointClient) ReportTaskComplete(arg0 context.Context, arg1 *agentendpointpb.ReportTaskCompleteRequest, arg2 ...gax.CallOption) (*agentendpointpb.ReportTaskCompleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReportTaskComplete", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.ReportTaskCompleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportTaskComplete indicates an expected call of ReportTaskComplete.
func (mr *MockAgentEndpointClientMockRecorder) ReportTaskComplete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportTaskComplete", reflect.TypeOf((*MockAgentEndpointClient)(nil).ReportTaskComplete), varargs...)
}

// ReportTaskProgress mocks base method.
func (m *MockAgentEndpointClient) ReportTaskProgress(arg0 context.Context, arg1 *agentendpointpb.ReportTaskProgressRequest, arg2 ...gax.CallOption) (*agentendpointpb.ReportTaskProgressResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReportTaskProgress", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.ReportTaskProgressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportTaskProgress indicates an expected call of ReportTaskProgress.
func (mr *MockAgentEndpointClientMockRecorder) ReportTaskProgress(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportTaskProgress", reflect.TypeOf((*MockAgentEndpointClient)(nil).ReportTaskProgress), varargs...)
}

// ReportVmInventory mocks base method.
func (m *MockAgentEndpointClient) ReportVmInventory(arg0 context.Context, arg1 *agentendpointpb.ReportVmInventoryRequest, arg2 ...gax.CallOption) (*agentendpointpb.ReportVmInventoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReportVmInventory", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.ReportVmInventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportVmInventory indicates an expected call of ReportVmInventory.
func (mr *MockAgentEndpointClientMockRecorder) ReportVmInventory(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportVmInventory", reflect.TypeOf((*MockAgentEndpointClient)(nil).ReportVmInventory), varargs...)
}

// StartNextTask mocks base method.
func (m *MockAgentEndpointClient) StartNextTask(arg0 context.Context, arg1 *agentendpointpb.StartNextTaskRequest, arg2 ...gax.CallOption) (*agentendpointpb.StartNextTaskResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartNextTask", varargs...)
	ret0, _ := ret[0].(*agentendpointpb.StartNextTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartNextTask indicates an expected call of StartNextTask.
func (mr *MockAgentEndpointClientMockRecorder) StartNextTask(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNextTask", reflect.TypeOf((*MockAgentEndpointClient)(nil).StartNextTask), varargs...)
}
