// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/osconfig/agentendpoint/v1alpha1/tasks.proto

package agentendpoint

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies the current agent behavior.
type TaskDirective int32

const (
	// Unspecified is invalid.
	TaskDirective_TASK_DIRECTIVE_UNSPECIFIED TaskDirective = 0
	// The task should continue to progress.
	TaskDirective_CONTINUE TaskDirective = 1
	// Task should not be started, or if already in progress, should stop
	// at first safe stopping point.  Task should be considered done and will
	// never repeat.
	TaskDirective_STOP TaskDirective = 2
)

var TaskDirective_name = map[int32]string{
	0: "TASK_DIRECTIVE_UNSPECIFIED",
	1: "CONTINUE",
	2: "STOP",
}

var TaskDirective_value = map[string]int32{
	"TASK_DIRECTIVE_UNSPECIFIED": 0,
	"CONTINUE":                   1,
	"STOP":                       2,
}

func (x TaskDirective) String() string {
	return proto.EnumName(TaskDirective_name, int32(x))
}

func (TaskDirective) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{0}
}

// Specifies the type of task to perform.
type TaskType int32

const (
	// Unspecified is invalid.
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	// The apply patches task.
	TaskType_APPLY_PATCHES TaskType = 1
	// The exec step task.
	TaskType_EXEC_STEP_TASK TaskType = 2
)

var TaskType_name = map[int32]string{
	0: "TASK_TYPE_UNSPECIFIED",
	1: "APPLY_PATCHES",
	2: "EXEC_STEP_TASK",
}

var TaskType_value = map[string]int32{
	"TASK_TYPE_UNSPECIFIED": 0,
	"APPLY_PATCHES":         1,
	"EXEC_STEP_TASK":        2,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}

func (TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{1}
}

// The intermediate states of applying patches.
type ApplyPatchesTaskProgress_State int32

const (
	// Unspecified is invalid.
	ApplyPatchesTaskProgress_STATE_UNSPECIFIED ApplyPatchesTaskProgress_State = 0
	// The agent has started the patch task.
	ApplyPatchesTaskProgress_STARTED ApplyPatchesTaskProgress_State = 4
	// The agent is currently downloading patches.
	ApplyPatchesTaskProgress_DOWNLOADING_PATCHES ApplyPatchesTaskProgress_State = 1
	// The agent is currently applying patches.
	ApplyPatchesTaskProgress_APPLYING_PATCHES ApplyPatchesTaskProgress_State = 2
	// The agent is currently rebooting the instance.
	ApplyPatchesTaskProgress_REBOOTING ApplyPatchesTaskProgress_State = 3
)

var ApplyPatchesTaskProgress_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	4: "STARTED",
	1: "DOWNLOADING_PATCHES",
	2: "APPLYING_PATCHES",
	3: "REBOOTING",
}

var ApplyPatchesTaskProgress_State_value = map[string]int32{
	"STATE_UNSPECIFIED":   0,
	"STARTED":             4,
	"DOWNLOADING_PATCHES": 1,
	"APPLYING_PATCHES":    2,
	"REBOOTING":           3,
}

func (x ApplyPatchesTaskProgress_State) String() string {
	return proto.EnumName(ApplyPatchesTaskProgress_State_name, int32(x))
}

func (ApplyPatchesTaskProgress_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{2, 0}
}

// The final states of applying patches.
type ApplyPatchesTaskOutput_State int32

const (
	// Unspecified is invalid.
	ApplyPatchesTaskOutput_STATE_UNSPECIFIED ApplyPatchesTaskOutput_State = 0
	// Applying patches completed successfully.
	ApplyPatchesTaskOutput_SUCCEEDED ApplyPatchesTaskOutput_State = 1
	// Applying patches completed successfully, but a reboot is required.
	ApplyPatchesTaskOutput_SUCCEEDED_REBOOT_REQUIRED ApplyPatchesTaskOutput_State = 2
	// Applying patches failed.
	ApplyPatchesTaskOutput_FAILED ApplyPatchesTaskOutput_State = 3
)

var ApplyPatchesTaskOutput_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "SUCCEEDED",
	2: "SUCCEEDED_REBOOT_REQUIRED",
	3: "FAILED",
}

var ApplyPatchesTaskOutput_State_value = map[string]int32{
	"STATE_UNSPECIFIED":         0,
	"SUCCEEDED":                 1,
	"SUCCEEDED_REBOOT_REQUIRED": 2,
	"FAILED":                    3,
}

func (x ApplyPatchesTaskOutput_State) String() string {
	return proto.EnumName(ApplyPatchesTaskOutput_State_name, int32(x))
}

func (ApplyPatchesTaskOutput_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{3, 0}
}

// The intermediate states of exec steps.
type ExecStepTaskProgress_State int32

const (
	// Unspecified is invalid.
	ExecStepTaskProgress_STATE_UNSPECIFIED ExecStepTaskProgress_State = 0
	// The agent has started the exec step task.
	ExecStepTaskProgress_STARTED ExecStepTaskProgress_State = 1
)

var ExecStepTaskProgress_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "STARTED",
}

var ExecStepTaskProgress_State_value = map[string]int32{
	"STATE_UNSPECIFIED": 0,
	"STARTED":           1,
}

func (x ExecStepTaskProgress_State) String() string {
	return proto.EnumName(ExecStepTaskProgress_State_name, int32(x))
}

func (ExecStepTaskProgress_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{5, 0}
}

// The final states of exec steps.
type ExecStepTaskOutput_State int32

const (
	// Unspecified is invalid.s
	ExecStepTaskOutput_STATE_UNSPECIFIED ExecStepTaskOutput_State = 0
	// The exec step completed normally.
	ExecStepTaskOutput_COMPLETED ExecStepTaskOutput_State = 1
	// The exec step was terminated because it took too long.
	ExecStepTaskOutput_TIMED_OUT ExecStepTaskOutput_State = 2
)

var ExecStepTaskOutput_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "COMPLETED",
	2: "TIMED_OUT",
}

var ExecStepTaskOutput_State_value = map[string]int32{
	"STATE_UNSPECIFIED": 0,
	"COMPLETED":         1,
	"TIMED_OUT":         2,
}

func (x ExecStepTaskOutput_State) String() string {
	return proto.EnumName(ExecStepTaskOutput_State_name, int32(x))
}

func (ExecStepTaskOutput_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{6, 0}
}

// A unit of work to be performed by the agent.
type Task struct {
	// Unique task id.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The type of task to perform.
	//
	// Task details must include the appropriate message based on this enum as
	// specified below:
	// APPLY_PATCHES = ApplyPatchesTask
	// EXEC_STEP = ExecStepTask;
	TaskType TaskType `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.TaskType" json:"task_type,omitempty"`
	// Current directive to the agent.
	TaskDirective TaskDirective `protobuf:"varint,3,opt,name=task_directive,json=taskDirective,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.TaskDirective" json:"task_directive,omitempty"`
	// Specific details about the current task to perform.
	//
	// Types that are valid to be assigned to TaskDetails:
	//	*Task_ApplyPatchesTask
	//	*Task_ExecStepTask
	TaskDetails          isTask_TaskDetails `protobuf_oneof:"task_details"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Task) GetTaskType() TaskType {
	if m != nil {
		return m.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (m *Task) GetTaskDirective() TaskDirective {
	if m != nil {
		return m.TaskDirective
	}
	return TaskDirective_TASK_DIRECTIVE_UNSPECIFIED
}

type isTask_TaskDetails interface {
	isTask_TaskDetails()
}

type Task_ApplyPatchesTask struct {
	ApplyPatchesTask *ApplyPatchesTask `protobuf:"bytes,4,opt,name=apply_patches_task,json=applyPatchesTask,proto3,oneof"`
}

type Task_ExecStepTask struct {
	ExecStepTask *ExecStepTask `protobuf:"bytes,5,opt,name=exec_step_task,json=execStepTask,proto3,oneof"`
}

func (*Task_ApplyPatchesTask) isTask_TaskDetails() {}

func (*Task_ExecStepTask) isTask_TaskDetails() {}

func (m *Task) GetTaskDetails() isTask_TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

func (m *Task) GetApplyPatchesTask() *ApplyPatchesTask {
	if x, ok := m.GetTaskDetails().(*Task_ApplyPatchesTask); ok {
		return x.ApplyPatchesTask
	}
	return nil
}

func (m *Task) GetExecStepTask() *ExecStepTask {
	if x, ok := m.GetTaskDetails().(*Task_ExecStepTask); ok {
		return x.ExecStepTask
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Task) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Task_ApplyPatchesTask)(nil),
		(*Task_ExecStepTask)(nil),
	}
}

// Message which instructs agent to apply patches.
type ApplyPatchesTask struct {
	// Specific information about how patches should be applied.
	PatchConfig *PatchConfig `protobuf:"bytes,1,opt,name=patch_config,json=patchConfig,proto3" json:"patch_config,omitempty"`
	// If true, the agent will report its status as it goes through the motions
	// but won't actually run any updates or perform any reboots.
	DryRun               bool     `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyPatchesTask) Reset()         { *m = ApplyPatchesTask{} }
func (m *ApplyPatchesTask) String() string { return proto.CompactTextString(m) }
func (*ApplyPatchesTask) ProtoMessage()    {}
func (*ApplyPatchesTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{1}
}

func (m *ApplyPatchesTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPatchesTask.Unmarshal(m, b)
}
func (m *ApplyPatchesTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPatchesTask.Marshal(b, m, deterministic)
}
func (m *ApplyPatchesTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPatchesTask.Merge(m, src)
}
func (m *ApplyPatchesTask) XXX_Size() int {
	return xxx_messageInfo_ApplyPatchesTask.Size(m)
}
func (m *ApplyPatchesTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPatchesTask.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPatchesTask proto.InternalMessageInfo

func (m *ApplyPatchesTask) GetPatchConfig() *PatchConfig {
	if m != nil {
		return m.PatchConfig
	}
	return nil
}

func (m *ApplyPatchesTask) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

// Information reported from the agent about applying patches execution.
type ApplyPatchesTaskProgress struct {
	// Required. The current state of this patch execution.
	State                ApplyPatchesTaskProgress_State `protobuf:"varint,1,opt,name=state,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskProgress_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ApplyPatchesTaskProgress) Reset()         { *m = ApplyPatchesTaskProgress{} }
func (m *ApplyPatchesTaskProgress) String() string { return proto.CompactTextString(m) }
func (*ApplyPatchesTaskProgress) ProtoMessage()    {}
func (*ApplyPatchesTaskProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{2}
}

func (m *ApplyPatchesTaskProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPatchesTaskProgress.Unmarshal(m, b)
}
func (m *ApplyPatchesTaskProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPatchesTaskProgress.Marshal(b, m, deterministic)
}
func (m *ApplyPatchesTaskProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPatchesTaskProgress.Merge(m, src)
}
func (m *ApplyPatchesTaskProgress) XXX_Size() int {
	return xxx_messageInfo_ApplyPatchesTaskProgress.Size(m)
}
func (m *ApplyPatchesTaskProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPatchesTaskProgress.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPatchesTaskProgress proto.InternalMessageInfo

func (m *ApplyPatchesTaskProgress) GetState() ApplyPatchesTaskProgress_State {
	if m != nil {
		return m.State
	}
	return ApplyPatchesTaskProgress_STATE_UNSPECIFIED
}

// Information reported from the agent about applying patches execution.
type ApplyPatchesTaskOutput struct {
	// Required. The final state of this task.
	State                ApplyPatchesTaskOutput_State `protobuf:"varint,1,opt,name=state,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskOutput_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ApplyPatchesTaskOutput) Reset()         { *m = ApplyPatchesTaskOutput{} }
func (m *ApplyPatchesTaskOutput) String() string { return proto.CompactTextString(m) }
func (*ApplyPatchesTaskOutput) ProtoMessage()    {}
func (*ApplyPatchesTaskOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{3}
}

func (m *ApplyPatchesTaskOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPatchesTaskOutput.Unmarshal(m, b)
}
func (m *ApplyPatchesTaskOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPatchesTaskOutput.Marshal(b, m, deterministic)
}
func (m *ApplyPatchesTaskOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPatchesTaskOutput.Merge(m, src)
}
func (m *ApplyPatchesTaskOutput) XXX_Size() int {
	return xxx_messageInfo_ApplyPatchesTaskOutput.Size(m)
}
func (m *ApplyPatchesTaskOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPatchesTaskOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPatchesTaskOutput proto.InternalMessageInfo

func (m *ApplyPatchesTaskOutput) GetState() ApplyPatchesTaskOutput_State {
	if m != nil {
		return m.State
	}
	return ApplyPatchesTaskOutput_STATE_UNSPECIFIED
}

// Message which instructs agent to execute the following command.
type ExecStepTask struct {
	// Details of the exec step to run.
	ExecStep             *ExecStep `protobuf:"bytes,1,opt,name=exec_step,json=execStep,proto3" json:"exec_step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExecStepTask) Reset()         { *m = ExecStepTask{} }
func (m *ExecStepTask) String() string { return proto.CompactTextString(m) }
func (*ExecStepTask) ProtoMessage()    {}
func (*ExecStepTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{4}
}

func (m *ExecStepTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStepTask.Unmarshal(m, b)
}
func (m *ExecStepTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStepTask.Marshal(b, m, deterministic)
}
func (m *ExecStepTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStepTask.Merge(m, src)
}
func (m *ExecStepTask) XXX_Size() int {
	return xxx_messageInfo_ExecStepTask.Size(m)
}
func (m *ExecStepTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStepTask.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStepTask proto.InternalMessageInfo

func (m *ExecStepTask) GetExecStep() *ExecStep {
	if m != nil {
		return m.ExecStep
	}
	return nil
}

// Information reported from the agent about the exec step execution.
type ExecStepTaskProgress struct {
	// Required. The current state of this exec step.
	State                ExecStepTaskProgress_State `protobuf:"varint,1,opt,name=state,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskProgress_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExecStepTaskProgress) Reset()         { *m = ExecStepTaskProgress{} }
func (m *ExecStepTaskProgress) String() string { return proto.CompactTextString(m) }
func (*ExecStepTaskProgress) ProtoMessage()    {}
func (*ExecStepTaskProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{5}
}

func (m *ExecStepTaskProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStepTaskProgress.Unmarshal(m, b)
}
func (m *ExecStepTaskProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStepTaskProgress.Marshal(b, m, deterministic)
}
func (m *ExecStepTaskProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStepTaskProgress.Merge(m, src)
}
func (m *ExecStepTaskProgress) XXX_Size() int {
	return xxx_messageInfo_ExecStepTaskProgress.Size(m)
}
func (m *ExecStepTaskProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStepTaskProgress.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStepTaskProgress proto.InternalMessageInfo

func (m *ExecStepTaskProgress) GetState() ExecStepTaskProgress_State {
	if m != nil {
		return m.State
	}
	return ExecStepTaskProgress_STATE_UNSPECIFIED
}

// Information reported from the agent about the exec step execution.
type ExecStepTaskOutput struct {
	// Required. The final state of the exec step.
	State ExecStepTaskOutput_State `protobuf:"varint,1,opt,name=state,proto3,enum=google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskOutput_State" json:"state,omitempty"`
	// Required. The exit code received from the script which ran as part of the exec step.
	ExitCode             int32    `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecStepTaskOutput) Reset()         { *m = ExecStepTaskOutput{} }
func (m *ExecStepTaskOutput) String() string { return proto.CompactTextString(m) }
func (*ExecStepTaskOutput) ProtoMessage()    {}
func (*ExecStepTaskOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_de81a21f3cce46a2, []int{6}
}

func (m *ExecStepTaskOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStepTaskOutput.Unmarshal(m, b)
}
func (m *ExecStepTaskOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStepTaskOutput.Marshal(b, m, deterministic)
}
func (m *ExecStepTaskOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStepTaskOutput.Merge(m, src)
}
func (m *ExecStepTaskOutput) XXX_Size() int {
	return xxx_messageInfo_ExecStepTaskOutput.Size(m)
}
func (m *ExecStepTaskOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStepTaskOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStepTaskOutput proto.InternalMessageInfo

func (m *ExecStepTaskOutput) GetState() ExecStepTaskOutput_State {
	if m != nil {
		return m.State
	}
	return ExecStepTaskOutput_STATE_UNSPECIFIED
}

func (m *ExecStepTaskOutput) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func init() {
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.TaskDirective", TaskDirective_name, TaskDirective_value)
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskProgress_State", ApplyPatchesTaskProgress_State_name, ApplyPatchesTaskProgress_State_value)
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskOutput_State", ApplyPatchesTaskOutput_State_name, ApplyPatchesTaskOutput_State_value)
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskProgress_State", ExecStepTaskProgress_State_name, ExecStepTaskProgress_State_value)
	proto.RegisterEnum("google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskOutput_State", ExecStepTaskOutput_State_name, ExecStepTaskOutput_State_value)
	proto.RegisterType((*Task)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.Task")
	proto.RegisterType((*ApplyPatchesTask)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTask")
	proto.RegisterType((*ApplyPatchesTaskProgress)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskProgress")
	proto.RegisterType((*ApplyPatchesTaskOutput)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ApplyPatchesTaskOutput")
	proto.RegisterType((*ExecStepTask)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTask")
	proto.RegisterType((*ExecStepTaskProgress)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskProgress")
	proto.RegisterType((*ExecStepTaskOutput)(nil), "google.cloud.osconfig.agentendpoint.v1alpha1.ExecStepTaskOutput")
}

func init() {
	proto.RegisterFile("google/cloud/osconfig/agentendpoint/v1alpha1/tasks.proto", fileDescriptor_de81a21f3cce46a2)
}

var fileDescriptor_de81a21f3cce46a2 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x8e, 0xdb, 0x44,
	0x14, 0xad, 0x93, 0xcd, 0x36, 0x7b, 0x37, 0x89, 0xdc, 0xa1, 0xa5, 0xe9, 0x4a, 0xc0, 0xca, 0x4f,
	0xab, 0x82, 0x6c, 0x1a, 0xa4, 0x0a, 0x28, 0x20, 0x39, 0xf6, 0xec, 0xae, 0x21, 0x8d, 0x8d, 0x3d,
	0x81, 0x2e, 0x42, 0x1a, 0x39, 0xf6, 0xd4, 0x6b, 0x1a, 0x3c, 0x96, 0x3d, 0x59, 0x35, 0x9f, 0xc0,
	0x3b, 0x1f, 0xc1, 0x47, 0xf0, 0x1f, 0x88, 0x37, 0xbe, 0x80, 0x6f, 0x40, 0x1e, 0x27, 0x4b, 0x12,
	0x41, 0xdb, 0x6c, 0xdf, 0x72, 0xef, 0xe4, 0x9e, 0x7b, 0xce, 0xbd, 0x67, 0xc6, 0xf0, 0x69, 0xc2,
	0x79, 0x32, 0x63, 0x46, 0x34, 0xe3, 0xf3, 0xd8, 0xe0, 0x65, 0xc4, 0xb3, 0xe7, 0x69, 0x62, 0x84,
	0x09, 0xcb, 0x04, 0xcb, 0xe2, 0x9c, 0xa7, 0x99, 0x30, 0xae, 0x1e, 0x85, 0xb3, 0xfc, 0x32, 0x7c,
	0x64, 0x88, 0xb0, 0x7c, 0x51, 0xea, 0x79, 0xc1, 0x05, 0x47, 0x1f, 0xd5, 0x95, 0xba, 0xac, 0xd4,
	0x57, 0x95, 0xfa, 0x46, 0xa5, 0xbe, 0xaa, 0x3c, 0xfa, 0x60, 0xd9, 0x27, 0xcc, 0x53, 0xe3, 0x79,
	0xca, 0x66, 0x31, 0x9d, 0xb2, 0xcb, 0xf0, 0x2a, 0xe5, 0x45, 0x0d, 0x77, 0xf4, 0xe5, 0x4e, 0x44,
	0xf2, 0x50, 0x44, 0x97, 0xf4, 0x27, 0x3e, 0x5d, 0xb2, 0xd1, 0x7e, 0x6f, 0xc2, 0x1e, 0x09, 0xcb,
	0x17, 0xe8, 0x3e, 0xdc, 0xae, 0x58, 0xd2, 0x34, 0xee, 0x2b, 0xc7, 0xca, 0xc9, 0x81, 0xbf, 0x5f,
	0x85, 0x4e, 0x8c, 0x02, 0x38, 0x90, 0x07, 0x62, 0x91, 0xb3, 0x7e, 0xe3, 0x58, 0x39, 0xe9, 0x0d,
	0x1e, 0xeb, 0xbb, 0x68, 0xd0, 0x2b, 0x7c, 0xb2, 0xc8, 0x99, 0xdf, 0x16, 0xcb, 0x5f, 0x68, 0x0a,
	0x3d, 0x09, 0x1a, 0xa7, 0x05, 0x8b, 0x44, 0x7a, 0xc5, 0xfa, 0x4d, 0x89, 0xfc, 0x64, 0x77, 0x64,
	0x7b, 0x05, 0xe1, 0x77, 0xc5, 0x7a, 0x88, 0x32, 0x40, 0x61, 0x9e, 0xcf, 0x16, 0x54, 0x8a, 0x66,
	0x25, 0xad, 0x8e, 0xfb, 0x7b, 0xc7, 0xca, 0xc9, 0xe1, 0xe0, 0xab, 0xdd, 0xfa, 0x98, 0x15, 0x8e,
	0x57, 0xc3, 0x54, 0x3d, 0xcf, 0x6f, 0xf9, 0x6a, 0xb8, 0x95, 0xab, 0x34, 0xb1, 0x97, 0x2c, 0xa2,
	0xa5, 0x60, 0x79, 0xdd, 0xab, 0x25, 0x7b, 0x7d, 0xbe, 0x5b, 0x2f, 0xfc, 0x92, 0x45, 0x81, 0x60,
	0xf9, 0xb2, 0x4f, 0x87, 0xad, 0xc5, 0xc3, 0x1e, 0x74, 0xea, 0xb9, 0x31, 0x11, 0xa6, 0xb3, 0x52,
	0xfb, 0x45, 0x01, 0x75, 0x9b, 0x1c, 0xfa, 0x11, 0x3a, 0xf5, 0x9e, 0xeb, 0x46, 0x72, 0x9f, 0x87,
	0x83, 0xcf, 0x76, 0xa3, 0x21, 0x01, 0x2d, 0xf9, 0x17, 0xff, 0x30, 0xff, 0x37, 0xa8, 0x8c, 0x12,
	0x17, 0x0b, 0x5a, 0xcc, 0x33, 0xb9, 0xb3, 0xb6, 0xbf, 0x1f, 0x17, 0x0b, 0x7f, 0x9e, 0x69, 0x7f,
	0x2b, 0xd0, 0xdf, 0xe6, 0xe2, 0x15, 0x3c, 0x29, 0x58, 0x59, 0xa2, 0x04, 0x5a, 0xa5, 0x08, 0x05,
	0x93, 0x64, 0x7a, 0x83, 0xd1, 0xdb, 0xcd, 0x7f, 0x05, 0xab, 0x07, 0x15, 0xe6, 0xb0, 0xf9, 0x97,
	0xd9, 0xf0, 0x6b, 0x7c, 0x2d, 0x85, 0x96, 0x4c, 0xa2, 0x7b, 0x70, 0x27, 0x20, 0x26, 0xc1, 0x74,
	0x32, 0x0e, 0x3c, 0x6c, 0x39, 0xa7, 0x0e, 0xb6, 0xd5, 0x5b, 0xe8, 0x10, 0x6e, 0x07, 0xc4, 0xf4,
	0x09, 0xb6, 0xd5, 0x3d, 0x74, 0x1f, 0xde, 0xb1, 0xdd, 0xef, 0xc7, 0x23, 0xd7, 0xb4, 0x9d, 0xf1,
	0x19, 0xf5, 0x4c, 0x62, 0x9d, 0xe3, 0x40, 0x55, 0xd0, 0x5d, 0x50, 0x4d, 0xcf, 0x1b, 0x5d, 0xac,
	0x67, 0x1b, 0xa8, 0x0b, 0x07, 0x3e, 0x1e, 0xba, 0x2e, 0x71, 0xc6, 0x67, 0x6a, 0x53, 0xfb, 0x53,
	0x81, 0x77, 0xb7, 0x99, 0xb9, 0x73, 0x91, 0xcf, 0x05, 0x62, 0x9b, 0x72, 0xbf, 0x7e, 0x3b, 0xb9,
	0x35, 0xe8, 0x7f, 0x88, 0x7d, 0xf6, 0x1a, 0xb1, 0x5d, 0x38, 0x08, 0x26, 0x96, 0x85, 0xb1, 0x8d,
	0x6d, 0x55, 0x41, 0xef, 0xc1, 0x83, 0xeb, 0x90, 0xd6, 0x4a, 0xa8, 0x8f, 0xbf, 0x9d, 0x38, 0x3e,
	0xb6, 0xd5, 0x06, 0x02, 0xd8, 0x3f, 0x35, 0x9d, 0x11, 0xb6, 0xd5, 0xa6, 0x16, 0x41, 0x67, 0xdd,
	0x88, 0xd5, 0x2b, 0x70, 0x6d, 0xee, 0xa5, 0xa1, 0x1e, 0xdf, 0xcc, 0xd7, 0x7e, 0x7b, 0xe5, 0x68,
	0xed, 0x37, 0x05, 0xee, 0xae, 0x77, 0xb9, 0x76, 0x4b, 0xb4, 0x39, 0xbe, 0xf3, 0x9b, 0xdf, 0xa0,
	0x57, 0x38, 0xe5, 0xc3, 0x37, 0x77, 0x8a, 0xa2, 0xfd, 0xa1, 0x00, 0x5a, 0xc7, 0x5d, 0xee, 0x39,
	0xdc, 0x24, 0x7a, 0x7a, 0x73, 0xa2, 0xff, 0xb7, 0x63, 0x74, 0x5c, 0x4d, 0x3e, 0x15, 0x34, 0xe2,
	0x71, 0xfd, 0xfe, 0xb6, 0xea, 0xe3, 0x76, 0x95, 0xb5, 0x78, 0xcc, 0xb4, 0x2f, 0x5e, 0xef, 0x02,
	0xcb, 0x7d, 0xea, 0x8d, 0xb0, 0x94, 0x52, 0x85, 0xc4, 0x79, 0x8a, 0x6d, 0xea, 0x4e, 0x88, 0xda,
	0x78, 0x78, 0x06, 0xdd, 0x8d, 0x67, 0x14, 0xbd, 0x0f, 0x47, 0xc4, 0x0c, 0xbe, 0xa1, 0xb6, 0xe3,
	0x63, 0x8b, 0x38, 0xdf, 0x6d, 0xc3, 0x75, 0xa0, 0x6d, 0xb9, 0x63, 0xe2, 0x8c, 0x27, 0x58, 0x55,
	0x50, 0x1b, 0xf6, 0x02, 0xe2, 0x7a, 0x6a, 0xe3, 0xe1, 0x08, 0xda, 0xab, 0x97, 0x1e, 0x3d, 0x80,
	0x7b, 0x12, 0x83, 0x5c, 0x78, 0xdb, 0xe5, 0x77, 0xa0, 0x2b, 0xaf, 0xd6, 0xda, 0x6d, 0x43, 0xd0,
	0xc3, 0xcf, 0xb0, 0x45, 0x03, 0x82, 0x3d, 0x5a, 0xd5, 0xa9, 0x8d, 0xe1, 0xaf, 0x0a, 0x7c, 0x1c,
	0xf1, 0x9f, 0x77, 0x1a, 0xe8, 0xb0, 0x55, 0x11, 0x28, 0x7f, 0xb8, 0x58, 0x16, 0x25, 0x7c, 0x16,
	0x66, 0x89, 0xce, 0x8b, 0xc4, 0x48, 0x58, 0x26, 0x3f, 0x78, 0x46, 0x7d, 0x14, 0xe6, 0x69, 0xf9,
	0x66, 0x9f, 0xcc, 0x27, 0x1b, 0xe9, 0xe9, 0xbe, 0x44, 0xf9, 0xe4, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6e, 0x65, 0x1b, 0xc3, 0x00, 0x08, 0x00, 0x00,
}
