// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by gapic-generator. DO NOT EDIT.

package agentendpoint_test

import (
	"context"
	"io"

	agentendpoint "cloud.google.com/go/osconfig/agentendpoint/apiv1alpha1"
	agentendpointpb "google.golang.org/genproto/googleapis/cloud/osconfig/agentendpoint/v1alpha1"
)

func ExampleNewClient() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use client.
	_ = c
}

func ExampleClient_ReceiveTaskNotification() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &agentendpointpb.ReceiveTaskNotificationRequest{
		// TODO: Fill request struct fields.
	}
	stream, err := c.ReceiveTaskNotification(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	for {
		resp, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			// TODO: handle error.
		}
		// TODO: Use resp.
		_ = resp
	}
}

func ExampleClient_ReportTaskStart() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &agentendpointpb.ReportTaskStartRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.ReportTaskStart(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleClient_ReportTaskProgress() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &agentendpointpb.ReportTaskProgressRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.ReportTaskProgress(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleClient_ReportTaskComplete() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &agentendpointpb.ReportTaskCompleteRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.ReportTaskComplete(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleClient_LookupEffectiveGuestPolicies() {
	ctx := context.Background()
	c, err := agentendpoint.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &agentendpointpb.LookupEffectiveGuestPoliciesRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.LookupEffectiveGuestPolicies(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}
